[project]
name = "camera-ml-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.3"
dependencies = [
    "opencv-python>=4.13.0.90",
    "tensorflow>=2.20.0",
]
